(cl:defpackage assignment_2_2023-srv
  (:use )
  (:export
   "GETTRGTPOS"
   "<GETTRGTPOS-REQUEST>"
   "GETTRGTPOS-REQUEST"
   "<GETTRGTPOS-RESPONSE>"
   "GETTRGTPOS-RESPONSE"
   "LASTSTATUS"
   "<LASTSTATUS-REQUEST>"
   "LASTSTATUS-REQUEST"
   "<LASTSTATUS-RESPONSE>"
   "LASTSTATUS-RESPONSE"
  ))

