# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from assignment_2_2023/Pos_Vel.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Pos_Vel(genpy.Message):
  _md5sum = "02c2eea77b57a6515b01afba1c028320"
  _type = "assignment_2_2023/Pos_Vel"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# custom.msg
float64 robpos_x
float64 robpos_y
float64 robvel_x
float64 robvel_y
"""
  __slots__ = ['robpos_x','robpos_y','robvel_x','robvel_y']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robpos_x,robpos_y,robvel_x,robvel_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Pos_Vel, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robpos_x is None:
        self.robpos_x = 0.
      if self.robpos_y is None:
        self.robpos_y = 0.
      if self.robvel_x is None:
        self.robvel_x = 0.
      if self.robvel_y is None:
        self.robvel_y = 0.
    else:
      self.robpos_x = 0.
      self.robpos_y = 0.
      self.robvel_x = 0.
      self.robvel_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.robpos_x, _x.robpos_y, _x.robvel_x, _x.robvel_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.robpos_x, _x.robpos_y, _x.robvel_x, _x.robvel_y,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.robpos_x, _x.robpos_y, _x.robvel_x, _x.robvel_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.robpos_x, _x.robpos_y, _x.robvel_x, _x.robvel_y,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
